version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn package
      - mv target/create-user-1.0.jar .
      - unzip create-user-1.0.jar
      - rm -rf target src buildspec.yml pom.xml create-user-1.0.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  files:
    - template-export.yml