AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: Creating a user for books API
  neo_user:
    Type: String
    Description: username for neo4j instance
  neo_password:
      Type: String
      Description: password for neo4j instance
  neo_url:
      Type: String
      Description: url for neo4j instance

Resources:
  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.openlight.lambda.CreateUserHandler
      Runtime: java8
      MemorySize: 300
      Environment:
        Variables:
          neo_user: !Ref 'neo_user'
          neo_url: !Ref 'neo_url'
          neo_password: !Ref 'neo_password'
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /users
            Method: post
  GetUser:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.openlight.lambda.GetUserHandler
        Runtime: java8
        MemorySize: 300
        Role:
          Fn::ImportValue:
            !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
        Events:
          GetEvent:
            Type: Api
            Properties:
              Path: /users/{username}
              Method: get
